---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Check for Python
  become: true
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: Install Python
  become: true
  raw: apt -y update && apt install -y python-minimal
  when: check_python.rc != 0

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present